#### The problem
apiVersion: v1
kind: Secret
metadata:
  name: app-sec1
data:
  APP1_PASSWORD: QWJjZEAxMjM0
---
apiVersion: v1
kind: Secret
metadata:
  name: app-sec2
data:
  APP2_PASSWORD: eHl6QDMyMQ==
---
---
kind: Pod
apiVersion: v1
metadata:
  name: debug-app-01
spec:
  containers:
    - name: debug
      image: rkalluru/debug
      envFrom:
      - secretRef:
          name: app-sec1
      - secretRef:
          name: app-sec2
---
kind: Pod
apiVersion: v1
metadata:
  name: debug-app-02
spec:
  containers:
    - name: debug
      image: rkalluru/debug
      envFrom:
      - secretRef:
          name: app-sec2


