apiVersion: v1
kind: Namespace
spec:
  name: example
  labels:
    istio-injection: enabled
---
kind: Pod
apiVersion: v1
metadata:
  name: demo
  namespace: example
spec:
  containers:
    - name: nginx
      image: nginx
